In [1]:
import numpy as np

In [2]:
# column vector
c = np.array([1,2,3])             # 3행 1열
print (c.shape)

# obtaining a particular entry
print (c[0])

(3,)
1


In [3]:
# row vector
r = np.array([ [1,2,3] ])        # 1행 3열   # 첫 번째 []는 row(행)을 의미함 -> 그 안의 []가 column(열)
print (r.shape)

(1, 3)


In [4]:
# obtaining a particular entry
print (r[0,1])

2


In [5]:
# 모든 값이 0인 2행 2열 matrix
a = np.zeros((2,2))
print (a)
# 모든 값이 1인 2행 2열 matrix
b = np.ones((2,2))
print (b)
             
# 모든 값을 7로 채운 2행 2열 matrix
c = np.full((2,2), 7)
print (c)
             
# 0과 1사이의 랜덤값으로 만든 2행 2열 matrix
d = np.random.random((2,2))
print (d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.10039022 0.99829307]
 [0.7201524  0.29753441]]


In [6]:
# creating a matrix
A = np.array([[1,2],[3,4],[5,6]])    # 3행 2열
print (A)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
# creating another matrix
B = np.array([[11,12,13,14],[15,16,17,18]]) # 2행 4열
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [8]:
# transpose a matrix
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
# 행렬 A, B의 곱  ->   (3,2) * (2,4) = (3,4)
np.dot(A,B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [10]:
# 행렬 B, A의 곱  ->  (2,4) * (3,2)  ->  사이즈가 맞지 않음
np.dot(B,A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [11]:
# 3 x 3 계수행렬 A, 3행 1열 상수벡터 b
A = np.array([[60, 5.5, 1],[65, 5.0, 0],[55, 6.0, 1]])
b = np.array([66, 70, 78])

In [12]:
# (i,i)값만 1, 나머지 값은 0   ->   단위행렬
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# 역행렬을 계산해주는 라이브러리
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [14]:
# 원소끼리 곱한 값이 나오므로 단위행렬이 되지 않음
A * A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [15]:
# dot함수를 사용해야 단위행렬이 됨
A.dot(A_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# A * x = b 식에서의 x값 구하기
x = A_inv.dot(b)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [17]:
# 역행렬 없이 한 번에 x값을 구할 수 있는 라이브러리
from numpy.linalg import solve
x = solve(A,b)
x

array([ -0.43478261,  19.65217391, -16.        ])